default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password

development:
  <<: *default
  database: myapp_development

test:
  adapter: postgresql
  encoding: unicode
  database: kutemy_db
  username: kutemy_db_user
  password: postgres
  host: dpg-cv6obarqf0us73f4pvn0-a
  port: 5432

production:
  <<: *default
  database: myapp_production
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
