default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DATABASE_HOST"] %> # render.comのデータベースホスト
  username: <%= ENV["DATABASE_USERNAME"] %> # render.comのユーザー名
  password: <%= ENV["DATABASE_PASSWORD"] %> # render.comのパスワード

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_ci_test # CI用のデータベース名

production:
  <<: *default
  database: myapp_production
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
